# ==============================================================================
# Powerlevel10k — Theme Loading
# MUST be sourced at the very end of .zshrc (after all plugins, aliases, functions)
# Order: ~/powerlevel10k → OMZ custom themes → fallback (whichever found first)
# ==============================================================================
if [[ -f ~/powerlevel10k/powerlevel10k.zsh-theme ]]; then
  source ~/powerlevel10k/powerlevel10k.zsh-theme
elif [[ -f ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/themes/powerlevel10k/powerlevel10k.zsh-theme ]]; then
  source ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/themes/powerlevel10k/powerlevel10k.zsh-theme
else
  print -ru2 -- "zsh_profile: powerlevel10k theme not found — see install.sh do_install_p10k"
fi

# ==============================================================================
# Powerlevel10k Configuration
# Generated by `p10k configure` interactive wizard
# Configures prompt segments, icons, colors, and transient prompt behavior
# Validates presence so a missing theme/config is reported instead of silently
# rendering a generic prompt (issue #33)
# ==============================================================================
if [[ -f ~/.p10k.zsh ]]; then
  source ~/.p10k.zsh
else
  print -ru2 -- "zsh_profile: ~/.p10k.zsh not found — run: p10k configure"
fi
