# ==============================================================================
# Powerlevel10k — Theme Loading
# MUST be sourced at the very end of .zshrc (after all plugins, aliases, functions)
# Order: ~/powerlevel10k → OMZ custom themes → fallback (whichever found first)
# ==============================================================================
if [[ -f ~/powerlevel10k/powerlevel10k.zsh-theme ]]; then
  source ~/powerlevel10k/powerlevel10k.zsh-theme
elif [[ -f ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/themes/powerlevel10k/powerlevel10k.zsh-theme ]]; then
  source ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/themes/powerlevel10k/powerlevel10k.zsh-theme
fi

# ==============================================================================
# Powerlevel10k Configuration
# Generated by `p10k configure` interactive wizard
# Configures prompt segments, icons, colors, and transient prompt behavior
# ==============================================================================
[[ -f ~/.p10k.zsh ]] && source ~/.p10k.zsh
